### ISSUE TITLE
对于数据储存方式的一点建议

### ISSUE THREAD

**Issue by kzw200015** [iyear/E5SubBot#3]
大部分情况下，我认为一个小工具不需要和`MySQL`捆绑，使用轻量级的`Sqlite`会更好，如果担心对C库的依赖也可以考虑使用`json`来储存数据

**Comment by iyear** [comment]
开发的过程可以在README以前的提交看到
一开始就是用sqlite的，但是编译的时候cgo各种出错，后来实在不行放弃了(目前用的goreleaser也不支持cgo)
初期也没考虑这么多，主要是想学习一下CRUD的基本语法和go对数据库的操作，所以能上啥就用啥了。
目前demo已经有100多的绑定了，refreshtoken很长，如果采用json的话怕数据文件太大

pr已经看到了，但是我对docker镜像制作没了解，待我研究一下……依赖mysql的话是不是还需要docker-compose?

**Comment by kzw200015** [comment]
关于`json`数据文件太大的问题，我觉得光一个mysql占的空间就已经够大了。可以看一下这个项目 [iovxw/rssbot](https://github.com/iovxw/rssbot)，它就是用`json`储存数据，储存的时候将`json`压缩了一下，体积并不会很大


为了方便的话还是用`docker-compose`比较好。当然手动管理也不是不行。可以参考一下我的docker-compose.yml
```
version: "3"
services:
  mysql:
    image: mariadb:10.4.12
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    restart: always
    container_name: mysql
  e5bot:
    build: ./e5bot
    volumes:
      - ./e5bot/config/config.yml:/root/config.yml
    restart: always
    container_name: e5bot
```
